import type { FastifyPluginAsync } from "fastify";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { prisma } from "../../lib/db.js";
import { presignUpload, publicUrl } from "../../lib/r2.js";
import { badRequest, forbidden, notFound } from "../../lib/errors.js";

// OWNED BY: feat/backend-media worktree.
// Implements: POST /media/upload-url (presigned R2 PUT), POST /media/:photoId/complete,
//   GET /media/:photoId  (see docs/API.md). Mounted under /media.
// Use: lib/r2.ts (presignUpload, publicUrl); prisma Photo (uploaded flag flips on complete);
//   key convention: `users/{userId}/{photoId}.{ext}`. Validate contentType is image/*.

const MAX_FILE_SIZE = 25 * 1024 * 1024; // 25 MB

// contentType -> file extension. Anything else falls back to "bin".
const EXT_BY_CONTENT_TYPE: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/jpg": "jpg",
  "image/png": "png",
  "image/heic": "heic",
  "image/webp": "webp",
};

function extForContentType(contentType: string): string {
  return EXT_BY_CONTENT_TYPE[contentType] ?? "bin";
}

const uploadUrlBody = z.object({
  contentType: z.string().min(1),
  fileSize: z.number().int().positive().max(MAX_FILE_SIZE),
});

const completeBody = z.object({
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  blurhash: z.string().min(1).optional(),
});

const photoIdParams = z.object({
  photoId: z.string().min(1),
});

type PhotoDtoInput = {
  id: string;
  r2Key: string;
  width: number | null;
  height: number | null;
  blurhash: string | null;
  createdAt: Date;
};

function toPhotoDto(photo: PhotoDtoInput) {
  return {
    id: photo.id,
    url: publicUrl(photo.r2Key),
    width: photo.width,
    height: photo.height,
    blurhash: photo.blurhash,
    createdAt: photo.createdAt.toISOString(),
  };
}

export const mediaRoutes: FastifyPluginAsync = async (app) => {
  // POST /media/upload-url — create a pending Photo + presigned PUT URL.
  app.post("/upload-url", { preHandler: app.authenticate }, async (req) => {
    const userId = req.userId!;

    const parsed = uploadUrlBody.safeParse(req.body);
    if (!parsed.success) throw badRequest("Invalid upload request", "validation_error");
    const { contentType, fileSize } = parsed.data;

    if (!contentType.startsWith("image/")) {
      throw badRequest("contentType must be an image/* type", "unsupported_media_type");
    }
    if (!Number.isFinite(fileSize) || fileSize <= 0 || fileSize > MAX_FILE_SIZE) {
      throw badRequest("fileSize must be a positive number under 25 MB", "file_too_large");
    }

    const ext = extForContentType(contentType);

    // Photo.id is generated by Prisma, but r2Key is required + unique at creation
    // time. Create with a unique placeholder key, then rewrite to the final
    // `users/{userId}/{photoId}.{ext}` key so the key embeds the real id.
    const photo = await prisma.$transaction(async (tx) => {
      const created = await tx.photo.create({
        data: {
          ownerId: userId,
          r2Key: `pending/${randomUUID()}`,
          uploaded: false,
        },
      });
      return tx.photo.update({
        where: { id: created.id },
        data: { r2Key: `users/${userId}/${created.id}.${ext}` },
      });
    });

    const uploadUrl = await presignUpload(photo.r2Key, contentType);

    return { photoId: photo.id, uploadUrl, r2Key: photo.r2Key };
  });

  // POST /media/:photoId/complete — confirm upload, set dimensions, return Photo DTO.
  app.post("/:photoId/complete", { preHandler: app.authenticate }, async (req) => {
    const userId = req.userId!;

    const params = photoIdParams.safeParse(req.params);
    if (!params.success) throw badRequest("Invalid photo id", "validation_error");

    const parsed = completeBody.safeParse(req.body);
    if (!parsed.success) throw badRequest("Invalid complete request", "validation_error");
    const { width, height, blurhash } = parsed.data;

    const photo = await prisma.photo.findUnique({ where: { id: params.data.photoId } });
    if (!photo) throw notFound("Photo not found");
    if (photo.ownerId !== userId) throw forbidden("Not the owner of this photo");

    const updated = await prisma.photo.update({
      where: { id: photo.id },
      data: { uploaded: true, width, height, blurhash: blurhash ?? null },
    });

    return toPhotoDto(updated);
  });

  // GET /media/:photoId — public Photo DTO. 404 if not found.
  app.get("/:photoId", async (req) => {
    const params = photoIdParams.safeParse(req.params);
    if (!params.success) throw badRequest("Invalid photo id", "validation_error");

    const photo = await prisma.photo.findUnique({ where: { id: params.data.photoId } });
    if (!photo) throw notFound("Photo not found");

    return toPhotoDto(photo);
  });
};
